# Generated by Django 6.0.3 on 2026-03-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('feriado', 'Feriado'), ('recesso', 'Recesso'), ('religioso', 'Religioso'), ('social', 'Social / Comemorativo'), ('mobilizacao', 'Semana de Mobilização'), ('institucional', 'Evento Institucional'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data_inicio'],
            },
        ),
    ]
